### ISSUE TITLE
文档格式混乱

### ISSUE THREAD

**Issue by huangbenben** [pingcap/docs-cn#2502]
File: [v3.0/overview.md](https://pingcap.com/docs-cn/v3.0/overview/)

官方文档PDF版本的，1289-1293页表格部分格式混乱。
the official  document with the format of PDF,on page 1289 to 1293, the appearance of table is ugly.

**Comment by anotherrachel** [comment]
@YiniXu9506 Please help locate the problem, thanks!

**Comment by TomShawn** [comment]
@huangbenben Thanks for pointing out! We have made enormous documentation improvements over the past seven to eight months since you created this issue. As I have confirmed that the v3.0 documentation PDF only has 1199 pages now, I'll close this stale issue for now. If you have found out further display issues in our doc PDF, you are welcome to open another issue.
![image](https://user-images.githubusercontent.com/41534398/98065002-89249f00-1e8e-11eb-9e7c-e7472312c624.png)
